version: '3'

services:

  telethon_downloader:
    image: jsavargas/telethon_downloader
    container_name: telethon_downloader
    restart: unless-stopped
    network_mode: host
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TG_AUTHORIZED_USER_ID=' #<telegram chat_id authorized>
      - 'TG_API_ID='
      - 'TG_API_HASH='
      - 'TG_BOT_TOKEN='
      - 'TG_PROGRESS_DOWNLOAD=True' #OPTIONAL
      - 'TZ=America/Santiago'
      - 'TG_MOVIES_PATH=Pelis'
      - 'TG_TV_SERIES_PATH=Series'
    volumes:
      - /path/to/config:/config
      - /path/to/download:/download
      - /path/to/download/torrent/watch:/watch
      - /path/to/multimedia:/multimedia
